parameters:
# Branch of the VMR to use (to push to for internal builds)
- name: vmrBranch
  type: string
  default: $(Build.SourceBranch)

- name: pool_Windows
  type: object
  default:
    name: $(defaultPoolName)
    image: $(poolImage_Windows)
    demands: ImageOverride -equals $(poolImage_Windows)
    os: windows

- name: primaryDependentJob
  type: string
  default: Windows_x64

- name: azureDevOpsOrg
  type: string
  default: dnceng

- name: azureDevOpsProject
  type: string
  default: internal
    
stages:
- stage: VMR_Final_Join
  displayName: VMR Final Join
  dependsOn: VMR_Vertical_Build
  variables:
  - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
    - group: Publish-Build-Assets
  - ${{ else }}:
    - name: dn-bot-dnceng-build-rw-code-rw
      value: ''

  - template: ../variables/vmr-build.yml
    parameters:
      vmrBranch: ${{ parameters.vmrBranch }}

  jobs:
  - job: VMR_Final_Join
    pool: ${{ parameters.pool_Windows }}

    templateContext:
      outputs:
      - output: pipelineArtifact
        path: $(Build.ArtifactStagingDirectory)/artifacts
        artifact: JoinedArtifacts
        condition: succeededOrFailed()

    steps:
    - checkout: self

    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: 'VerticalManifests'
        targetPath: $(Build.ArtifactStagingDirectory)/VerticalManifests

    - script: $(Build.SourcesDirectory)/build.cmd 
        -ci
        /p:DotNetBuildPass=final
        /p:VerticalManifestsPath=$(Build.ArtifactStagingDirectory)/VerticalManifests
        /p:MainVertical=${{ parameters.primaryDependentJob }}
        /p:BuildId=$(Build.BuildId)
        /p:AzureDevOpsToken=$(dn-bot-dnceng-build-rw-code-rw)
        /p:AzureDevOpsOrg=${{ parameters.azureDevOpsOrg }}
        /p:AzureDevOpsProject=${{ parameters.azureDevOpsProject }}
        /p:TmpFolder=$(Agent.TempDirectory)
        /p:OutputFolder=$(Build.ArtifactStagingDirectory)/artifacts
      displayName: 'VMR Final Join'

    - ${{ if or(ne(variables['System.TeamProject'], 'internal'), eq(variables['Build.Reason'], 'PullRequest')) }}:
      - publish: $(Build.ArtifactStagingDirectory)/artifacts
        artifact: JoinedArtifacts
        displayName: Publish Artifacts
        condition: succeededOrFailed()
        continueOnError: true